# Goldsky Mirror Pipeline: Polymarket User Balances
# Dataset: polymarket.user_balances
#
# This pipeline syncs Polymarket user balance data to Supabase.
# Contains current share holdings for NAV/unrealized PnL calculation.
#
# Usage:
#   goldsky pipeline apply infra/goldsky/polymarket-user-balances.yaml

name: polymarket-user-balances
apiVersion: 3

sources:
  polymarket_user_balances:
    type: dataset
    dataset_name: polymarket.user_balances
    version: 1.0.0

transforms: {}

sinks:
  supabase_sink:
    type: postgres
    from: polymarket_user_balances
    secret_name: SUPABASE_POLYMARKET_DB
    table: goldsky_user_balances
    schema: public
    description: Sync Polymarket user balances to Supabase
