# Goldsky Mirror Pipeline: Polymarket Order Filled Events
# Dataset: polymarket.order_filled
#
# This pipeline syncs Polymarket order fill events to Supabase.
# Contains timestamped trade events for 7d/30d metrics, win rate, and drawdown.
#
# Usage:
#   goldsky pipeline apply infra/goldsky/polymarket-order-filled.yaml

name: polymarket-order-filled
apiVersion: 3

sources:
  polymarket_order_filled:
    type: dataset
    dataset_name: polymarket.order_filled
    version: 1.0.0

transforms: {}

sinks:
  supabase_sink:
    type: postgres
    from: polymarket_order_filled
    secret_name: SUPABASE_POLYMARKET_DB
    table: goldsky_order_filled
    schema: public
    description: Sync Polymarket order filled events to Supabase
