# Goldsky Mirror Pipeline: Polymarket User Positions
# Dataset: polymarket.user_positions
#
# This pipeline syncs Polymarket user position data to Supabase.
# Contains aggregated position data including realized_pnl, total_bought, avg_price.
#
# Usage:
#   goldsky pipeline apply infra/goldsky/polymarket-user-positions.yaml

name: polymarket-user-positions
apiVersion: 3

sources:
  polymarket_user_positions:
    type: dataset
    dataset_name: polymarket.user_positions
    version: 1.0.0

transforms: {}

sinks:
  supabase_sink:
    type: postgres
    from: polymarket_user_positions
    secret_name: SUPABASE_POLYMARKET_DB
    table: goldsky_user_positions
    schema: public
    description: Sync Polymarket user positions to Supabase
